server:
  port: 8762
  ssl:
    enabled: true
    key-store: classpath:server-keystore.jks
    key-store-password: mdj1646MDJ
    trust-store: classpath:server-truststore.jks
    trust-store-password: mdj1646MDJ

spring:
  application:
    name: "proxy-server"

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  retryable: true
  ignore-security-headers: false
  sensitiveHeaders: Cookie,Set-Cookie
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
