server:
  port: 8762
spring:
  application:
    name: "proxy-server"

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
#  routes:
#    paypal:
#      path: "/paypal/**"
#      service-id : "paypal-service"
#  ignored-services: "*"
  retryable: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000