server:
  port: 8762
spring:
  application:
    name: "proxy-server"

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  retryable: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

#
#security:
#  oauth2:
#    client:
#      client-id: 0oai5o6bfsGGPvAta0h7
#      client-secret: uHiaKJ23Loz_REKlpuLj5mC8CbcNNgfNQLCswxYf
#      access-token-uri: https://dev-332551.oktapreview.com/oauth2/default/v1/token
#      user-authorization-uri: https://dev-332551.oktapreview.com/oauth2/default/v1/authorize
#      scope: openid profile email
#    resource:
#      user-info-uri: https://dev-332551.oktapreview.com/oauth2/default/v1/userinfo